// <auto-generated />
using System;
using FileAnalysis.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace FileAnalysis.Infrastructure.Migrations
{
    [DbContext(typeof(FileAnalysisDbContext))]
    partial class FileAnalysisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileAnalysis.Core.Models.CleanupSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid?>("DuplicateOfFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuarantinePath")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SuggestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DuplicateOfFileId");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("cleanup_suggestions", (string)null);
                });

            modelBuilder.Entity("FileAnalysis.Core.Models.DirectorySurveyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ClassificationReason")
                        .HasColumnType("text");

                    b.Property<string>("ClassificationSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<int>("DirectFileCount")
                        .HasColumnType("integer");

                    b.Property<long>("DirectSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool?>("ExcludeDecision")
                        .HasColumnType("boolean");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanRootPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SurveyedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("TopExtensions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("TotalFileCount")
                        .HasColumnType("integer");

                    b.Property<long>("TotalSizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("ScanRootPath");

                    b.ToTable("directory_survey_entries", (string)null);
                });

            modelBuilder.Entity("FileAnalysis.Core.Models.FileAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsDuplicateCandidate")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Topics")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("UsefulnessScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("file_analyses", (string)null);
                });

            modelBuilder.Entity("FileAnalysis.Core.Models.FileContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("file_contents", (string)null);
                });

            modelBuilder.Entity("FileAnalysis.Core.Models.IndexedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FileCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FileModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Md5Hash")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Extension");

                    b.HasIndex("IndexedAt");

                    b.HasIndex("Md5Hash")
                        .HasFilter("\"Md5Hash\" IS NOT NULL");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("FileAnalysis.Core.Models.CleanupSuggestion", b =>
                {
                    b.HasOne("FileAnalysis.Core.Models.IndexedFile", "DuplicateOf")
                        .WithMany()
                        .HasForeignKey("DuplicateOfFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FileAnalysis.Core.Models.IndexedFile", "File")
                        .WithOne()
                        .HasForeignKey("FileAnalysis.Core.Models.CleanupSuggestion", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuplicateOf");

                    b.Navigation("File");
                });

            modelBuilder.Entity("FileAnalysis.Core.Models.FileAnalysisResult", b =>
                {
                    b.HasOne("FileAnalysis.Core.Models.IndexedFile", "File")
                        .WithOne("Analysis")
                        .HasForeignKey("FileAnalysis.Core.Models.FileAnalysisResult", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("FileAnalysis.Core.Models.FileContent", b =>
                {
                    b.HasOne("FileAnalysis.Core.Models.IndexedFile", "File")
                        .WithMany("Contents")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("FileAnalysis.Core.Models.IndexedFile", b =>
                {
                    b.Navigation("Analysis");

                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
